server.port:${PORT:9999}

spring.datasource.url:${DB_URL:jdbc:mysql://localhost/learnsphere}
spring.datasource.username:${DB_USERNAME:root}
spring.datasource.password:${DB_PASSWORD:Bharani@1745933}

spring.jpa.hibernate.ddl-auto:update